### ISSUE TITLE
bazel test //... fails

### ISSUE THREAD

**Issue by gonzojive** [gTile/gTile#287]
gTile would benefit from continuous integration testing. The current test cases fail to build. `bazel test //...` should succeed.

```
$ bazel test //:tests
INFO: Analyzed target //:tests (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 0 test targets...
ERROR: /home/red/git/gTile/BUILD.bazel:158:11: Compiling TypeScript (devmode) //:tests failed: (Exit 1): tsc_wrapped.sh failed: error executing command bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh @@bazel-out/k8-fastbuild/bin/tests_es5_tsconfig.json
tilespec.spec.ts:4:26 - error TS2305: Module '"gtile/tilespec"' has no exported member 'parsePreset'.

4 import {LineSegment, XY, parsePreset, adjoiningSides, Edges, Side, Rect, Size, GridSize, parseGridSizesIgnoringErrors} from './tilespec';
                           ~~~~~~~~~~~
tilespec.spec.ts:31:26 - error TS7006: Parameter 'x' implicitly has an 'any' type.

31                     .map(x => x.toString())
                            ~

Target //:tests failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by gonzojive** [comment]
I believe https://github.com/gTile/gTile/pull/266 is responsible for the breakage.

**Comment by gonzojive** [comment]
Tests should also be before each release and probably integrated into the release script.

**Comment by gonzojive** [comment]
With some changes, I got the tests to run, and they fail:

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:testing
-----------------------------------------------------------------------------
Randomized with seed 82913
Started
[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m

Failures:
1) TileSpec.parsePreset success cases "3x3 0:0 1:1, 2x2 0:0 0:0" roundtrips to "3x3 0:0 1:1, 2x2 0:0 0:0"
  Message:
[31m    Error: Failed to parse 0 in tuple 0:0[0m
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at roundtrip (tilespec.spec.ts:31:24)
        at UserContext.<anonymous> (tilespec.spec.ts:35:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

2) TileSpec.parsePreset success cases "3x3 0:0 1:1,     0:0 0:0, 4x4 0:0 0:0,     0:2 3:3" roundtrips to "3x3 0:0 1:1, 3x3 0:0 0:0, 4x4 0:0 0:0, 4x4 0:2 3:3"
  Message:
[31m    Error: Failed to parse 0 in tuple 0:0[0m
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at roundtrip (tilespec.spec.ts:31:24)
        at UserContext.<anonymous> (tilespec.spec.ts:35:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

3) TileSpec.parsePreset success cases "3x3 0:0 1:1, 0:0 0:0" roundtrips to "3x3 0:0 1:1, 3x3 0:0 0:0"
  Message:
[31m    Error: Failed to parse 0 in tuple 0:0[0m
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at roundtrip (tilespec.spec.ts:31:24)
        at UserContext.<anonymous> (tilespec.spec.ts:35:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

4) TileSpec.isFullscreen "3x3 0:0 2:2" should have fullscreen = true
  Message:
[31m    Error: Failed to parse 0 in tuple 0:0[0m
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at UserContext.<anonymous> (tilespec.spec.ts:60:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

5) TileSpec.isFullscreen "3x10 0:0 2:9" should have fullscreen = true
  Message:
[31m    Error: Failed to parse 0 in tuple 0:0[0m
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at UserContext.<anonymous> (tilespec.spec.ts:60:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

6) TileSpec.isFullscreen "3x3 0:0 1:1" should have fullscreen = false
  Message:
[31m    Error: Failed to parse 0 in tuple 0:0[0m
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at UserContext.<anonymous> (tilespec.spec.ts:60:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

47 specs, 6 failures
Finished in 0.059 seconds
Randomized with seed 82913 (jasmine --random=true --seed=82913)

```

**Comment by scherepanov** [comment]
Hi @gonzojive 
Can you help to fix it?

**Comment by gonzojive** [comment]
I would prefer if the author of the breakage fixed the tests. I have made the tests build, but they are still failing.

**Comment by gonzojive** [comment]
Recent failure:

```
$ bazel test --test_output=errors //...
Loading: 
Loading: 0 packages loaded
Analyzing: 26 targets (0 packages loaded, 0 targets configured)
INFO: Analyzed 26 targets (0 packages loaded, 0 targets configured).
INFO: Found 25 targets and 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
FAIL: //:testing (see /home/red/.cache/bazel/_bazel_red/726f06adb8d3c1486efd7243dbbfe8e4/execroot/gtile/bazel-out/k8-fastbuild/testlogs/testing/test.log)
INFO: From Testing //:testing:
==================== Test output for //:testing:
Randomized with seed 23881
Started
.........................................FFFFFF

Failures:
1) TileSpec.isFullscreen "3x3 0:0 1:1" should have fullscreen = false
  Message:
    Error: Failed to parse 0 in tuple 0:0
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at UserContext.<anonymous> (tilespec.spec.ts:61:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

2) TileSpec.isFullscreen "3x3 0:0 2:2" should have fullscreen = true
  Message:
    Error: Failed to parse 0 in tuple 0:0
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at UserContext.<anonymous> (tilespec.spec.ts:61:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

3) TileSpec.isFullscreen "3x10 0:0 2:9" should have fullscreen = true
  Message:
    Error: Failed to parse 0 in tuple 0:0
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at UserContext.<anonymous> (tilespec.spec.ts:61:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

4) TileSpec.parsePreset success cases "3x3 0:0 1:1, 2x2 0:0 0:0" roundtrips to "3x3 0:0 1:1, 2x2 0:0 0:0"
  Message:
    Error: Failed to parse 0 in tuple 0:0
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at roundtrip (tilespec.spec.ts:31:24)
        at UserContext.<anonymous> (tilespec.spec.ts:35:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

5) TileSpec.parsePreset success cases "3x3 0:0 1:1,     0:0 0:0, 4x4 0:0 0:0,     0:2 3:3" roundtrips to "3x3 0:0 1:1, 3x3 0:0 0:0, 4x4 0:0 0:0, 4x4 0:2 3:3"
  Message:
    Error: Failed to parse 0 in tuple 0:0
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at roundtrip (tilespec.spec.ts:31:24)
        at UserContext.<anonymous> (tilespec.spec.ts:35:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

6) TileSpec.parsePreset success cases "3x3 0:0 1:1, 0:0 0:0" roundtrips to "3x3 0:0 1:1, 3x3 0:0 0:0"
  Message:
    Error: Failed to parse 0 in tuple 0:0
  Stack:
    Error: Failed to parse 0 in tuple 0:0
        at TupleHolder._validateCoordinate (tilespec.ts:176:19)
        at TupleHolder._validateTuple (tilespec.ts:162:14)
        at new TupleHolder (tilespec.ts:119:14)
        at parseSinglePreset (preset_parser.ts:38:15)
        at preset_parser.ts:26:24
        at <Jasmine>
        at Object.parsePreset (preset_parser.ts:14:18)
        at roundtrip (tilespec.spec.ts:31:24)
        at UserContext.<anonymous> (tilespec.spec.ts:35:20)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

47 specs, 6 failures
Finished in 0.06 seconds
Randomized with seed 23881 (jasmine --random=true --seed=23881)
================================================================================
INFO: Elapsed time: 0.457s, Critical Path: 0.30s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//:testing                                                               FAILED in 0.2s
```

**Comment by scherepanov** [comment]
I will fix it when will have some free time from my day job....

**Comment by scherepanov** [comment]
Fixed
